START TRANSACTION;

  USE `REDCAP_DB_NAME`;
  SET AUTOCOMMIT=0;
  SET UNIQUE_CHECKS=0;
  SET FOREIGN_KEY_CHECKS=0;

  # WRITE SQL HERE FOR ANY DATA YOU NEED TO POPULATE IN ORDER TO TEST YOUR PLUGIN(S)

 COMMIT;